# Generated by Django 4.2 on 2023-04-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=10000)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('downvote_count', models.PositiveIntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user', to='users.users')),
                ('downvotes_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downvotes_user', to='users.users')),
                ('upvotes_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upvotes_user', to='users.users')),
            ],
        ),
    ]
