# Generated by Django 4.2 on 2023-04-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_created', to='users.users'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='downvotes_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_downvoted', to='users.users'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='upvotes_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_upvoted', to='users.users'),
        ),
    ]
