# Generated by Django 4.2 on 2023-06-11 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_community_description'),
        ('posts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(default=None, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
