# Generated by Django 4.2 on 2023-06-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_body_alter_posts_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ManyToManyField(related_name='post', to='posts.postsimages'),
        ),
    ]
