# Generated by Django 4.2 on 2023-06-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postsimages_posts_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsImages',
            new_name='PostsImagesStore',
        ),
    ]
