# Generated by Django 4.2 on 2023-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_postsimages_postsimagesstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsimagesstore',
            name='image_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postsimagesstore',
            name='image',
            field=models.ImageField(upload_to='userassets/posts_images/'),
        ),
    ]
