# Generated by Django 4.2 on 2023-06-17 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_postsimagesstore_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='downvotes_user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='upvotes_user',
        ),
        migrations.AddField(
            model_name='posts',
            name='downvotes_user',
            field=models.ManyToManyField(null=True, related_name='posts_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='upvotes_user',
            field=models.ManyToManyField(null=True, related_name='posts_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
