# Generated by Django 4.2 on 2023-06-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_posts_downvotes_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='downvotes_user',
            new_name='downvotes_users',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='upvotes_user',
            new_name='upvotes_users',
        ),
    ]
