# Generated by Django 4.2 on 2023-06-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_downvotes_user_posts_downvotes_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='upvote_count',
        ),
    ]
