# Generated by Django 4.2 on 2023-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='participants',
            field=models.ManyToManyField(related_name='communities_joined', to='users.users'),
        ),
    ]
