# Generated by Django 4.2 on 2023-04-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('community', '0002_alter_community_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of', to='users.users'),
        ),
    ]
