# Generated by Django 4.2 on 2023-05-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='admin',
            new_name='moderator',
        ),
    ]
