# Generated by Django 4.2 on 2023-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='icon_path',
            field=models.ImageField(default=None, null=True, upload_to='community_icons/'),
        ),
    ]
