# Generated by Django 4.2 on 2023-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
