# Generated by Django 4.2 on 2023-05-29 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_rename_admin_community_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
